backend:
  name: git-gateway
  repo: tkhquang/tkhquang-blog
  branch: NETLIFY_CMS_BRANCH # Will be replaced during build with the current branch
media_folder: "/src/assets/uploads/images"
public_folder: "/src/assets/uploads/images"
collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    extension: 'md'
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Created At", name: "created_at", widget: "datetime"}
      - {label: "Updated At", name: "updated_at", widget: "datetime", required: false, default: ""}
      - {label: "Published", name: "published", widget: "boolean", default: true}
      - label: "Category"
        name: "category"
        widget: "relation"
        collection: "categories"
        searchFields: ["title", "slug"]
        valueField: "slug"
        displayFields: ["title"]
        multiple: false
      - label: "Tags"
        name: "tags"
        widget: "list"
        allow_add: true
        default: ["Random"]
      - {label: "Cover Image", name: "cover_image", widget: "image", required: false}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "categories"
    label: "Categories"
    folder: "content/categories"
    create: true
    slug: "{{slug}}"
    extension: 'md'
    identifier_field: "slug"
    fields:
      - {label: "title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
